// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxmglqvrjkfizzorfljp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54bWdscXZyamtmaXp6b3JmbGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODkwOTgsImV4cCI6MjA3MDI2NTA5OH0.5PQarYQcewP8ZYMCP4jJcVGtEAVEEJmmZxVlIGGiN_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});